version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=bc2412
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
