server:
  port: 8081

api:
  crypto-web:
    coin-market:
      url:
        base: "http://localhost:8085"
        version: "crypto/api/v1"
        cachedCoinsMarketsEndpoint: "/cache/coin/market"
      param:
        vsCurrency: "usd"
        ids:
        order: "market_cap_desc"
        per-page: 100
        page: 1
        sparkline: false
        price-change-percentage: "1h"
      return:
        no-of-items: 50