api:
  jsonplaceholder:
    domain: "rt.data.gov.hk/v1/transport/mtr"
    endpoints:
      schedules: "/getSchedule.php"

# Default configuration (used when no profile is specified or 'default' is active)
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/bc2412
    username: postgres
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Profile-specific configuration separator
---
# Test profile configuration (activated when 'test' profile is active)
spring:
  config:
    activate:
      on-profile: test  
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true