#server.port
server:
  port: 8100

#spring.datasource.driverClassName
#spring.datasource.url
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/bc2412"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true  # show sql command in terminal
  hibernate.ddl-auto: update

api:
  jsonplaceholder:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users"