FROM openjdk:17
LABEL maintainer="wanming1012@gmail.com"
ADD target/bc-mtr-station-0.0.1-SNAPSHOT.jar bc-mtr-station-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "bc-mtr-station-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080